name: GunGame
main: me.Jared.GunGame
version: 0.1
api-version: 1.20
commands:
  gungame:
    description: GunGame command!!
    usage: "/<command> [join|leave]"
  gg:
    description: GunGame command!!
    usage: "/<command> [join|leave]}"