name: Event
main: me.Jared.Event
version: 1.0
depend: [Kits]
api-version: 1.20
commands:
 event:
  description: Event commands /event help for help
 team:
  description: Team commands /team help for help