name: Grenades
main: me.Jared.GrenadesMain
version: 1.0
api-version: 1.20
commands:
 grenades:
  description: Give you all the grenades.
permissions:
 grenades:
  description: Permission node for getting grenades through commands