name: Duels
main: me.Jared.Duels
version: 0.1
depend: [PlaceholderAPI]
api-version: 1.20
commands:
  duel:
    description: Duels command!!
    usage: "/<command> [join,leave, set, accept, deny, list, remove, setspawn]"