name: Warz
main: me.Jared.Warz
version: 1.0
api-version: 1.21
depend: [WorldEdit, WorldGuard, Boosters]
softdepend: [CombatLogX]
commands:
 setzone:
  description: Sets a zone 1-6 based on the cuboid selection
 setloot:
  description: Sets the item in your hand to loot in the loot table
 addspawnpoint:
  descriptoin: Adds a spawnpoint to the config
 warz:
  description: Puts you in warz!
 warz2:
  description: Puts you in warz2!
 warz3:
  description: Puts you in warz3!