name: MiniGame
main: me.Jared.MiniGame
version: 0.1
api-version: 1.20
commands:
  sg:
   description: SurvivalGames command!
   usage: /<command> [join|leave]
  survivalgames: 
   description: SurvivalGames command!
   usage: /<command> [join|leave]
  spectate: 
   description: Spectate players who are playing!
  setloot:
  setchest: