name: MiniGame
main: me.Jared.MiniGame
version: 0.1
api-version: 1.20
depend: [PlaceholderAPI]
commands:
  sg:
   description: SurvivalGames command!
   usage: /<command> [join|leave]
  survivalgames: 
   description: SurvivalGames command!
   usage: /<command> [join|leave]
  spectate: 
   description: Spectate players who are playing!
  minigame:
   description: Access certain things like setloot
  setchest:
   description: Look at a chest to set it to a certain tier for battle royale mode