main: main.java.me.jared.food.Sugar
name: Food
version: 1.0
description: Food!
api-version: 1.20
commands:
  foodparticles:
    description: Change the amount of particles the food makes when you eat it.
    usage: /<command> <amount>
