name: Stats
main: me.Jared.Stats
version: 1.0
api-version: 1.20
commands:
  givegems:
    description: Gives gems to players.
  removegems:
    description: Removes gems from players.
  shop:
    description: A shop with items and prices.
  rank:
    description: Give ranks to players.
  killstreak:
    description: Toggles whether there is killstreak rewards
